language: csharp

dotnet: 3.1

script:
  - dotnet build Calc.sln -c Release
  - dotnet test -c Release --no-build Calc_Tests/Calc_Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash)
